googleadwordssamad/myproject/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='template_main'),
    path('groups/', views.groups, name='template_groups'),
    path('keywords/', views.keywords, name='template_keywords'),
    path('campaigns/', views.campaigns, name='template_campaigns'),
    path('show/', views.show, name='template_show'),
    path('showkeywords/', views.showkeywords, name='template_show'),
    path('ruleEngine/', views.ruleEngine, name='template_ruleEngine'),
    path('rule_keywords/', views.rule_keywords, name='rule_keywords'),
    path('rule_adgroups/', views.rule_adgroups, name='rule_adgroups'),
    path('rule_campaign/', views.rule_campaign, name='rule_campaign'),
    path('addRules/', views.addRules, name='addRules'),
    path('createRecipe/', views.createRecipe, name='createRecipe'),
    path('recipe_dash/', views.recipe_dash, name='recipe_dash'),
    path('recipeSettings/', views.recipeSettings, name='recipeSettings'),


    path('condition/', views.condition, name='condition'),
    path('action/', views.action, name='action'),
    path('ajaxaction/', views.ajax_action, name='ajax_action'),
    path('ajax_action_options/', views.ajax_action_options, name='ajax_action'),

    path('adscheduler/',views.ad_scheduler,name='adScheduler')
    # path('buildrecipe/', views.buildRecipe, name='buildRecipe')

]

googleadwordssamad/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include


urlpatterns = [
    path('admin/', admin.site.urls),
    url('myproject/', include('googleadwordssamad.myproject.urls')),
    url('', include('googleadwordssamad.myproject.urls'))
]

googleadwordssamad/myproject/forms.py
import datetime

from django import forms
from django.contrib.admin.widgets import AdminDateWidget
from django.forms import DateInput
from .models import AdwordsCampaign, AdwordsCampaignGroup, AdwordsCampaignKeywords, Rule_Engine_Recipe

STATUS_CHOICES = [('U', 'UNKNOWN'), ('E', 'ENABLED'), ('P', 'PAUSED'), ('R', 'REMOVED')]
CHANNEL_TYPE = (('DISPLAY', 'DISPLAY'), ('SEARCH', 'SEARCH'))
FILTER_CHOICES = (('ENABLED', 'ENABLED'), ('PAUSED', 'PAUSED'))
CAMPAIGN_CHOICES = [(c.campaign_id, c.name) for c in AdwordsCampaign.objects.all()]

GROUP_CHOICES = list()
KEYWORD_CHOICES = list()
CAMPAIGN_CHOICES.append((None, 'Select Campaign'))
KEYWORD_CHOICES.append((None, 'Select Keyword'))
GROUP_CHOICES.append((None, 'Select Adgroup'))

days = [('all', 'All Days'), ('workdays', 'Monday - Friday'), ('weekend', 'Saturdays - Sundays'), ('MONDAY', 'Monday'),
        ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'),
        ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')]
time = [(val, f'{(val // 60) % 59:02}' + ':' + f'{val % 60:02}') for val in range(45, 15 * 96, 15)]
for o in AdwordsCampaignKeywords.objects.all():
    g = AdwordsCampaignGroup.objects.get(pk=o.group_id)
    g_name = g.name
    c_name = AdwordsCampaign.objects.get(pk=g.campaign_id).name
    KEYWORD_CHOICES.append((o.keyword_id, o.text + " [Group: " + g_name + " , Campaign: " + c_name + " ]"))

for p in AdwordsCampaignGroup.objects.all():
    c_name = AdwordsCampaign.objects.get(pk=p.campaign_id).name
    GROUP_CHOICES.append((p.group_id, p.name + " [Campaign: " + c_name + " ]"))


class add_campaign(forms.Form):
    name = forms.CharField(label="Enter Campaign name:", max_length=100)
    status = forms.ChoiceField(label="Status", choices=STATUS_CHOICES)
    channelType = forms.ChoiceField(label="Channel Type", choices=CHANNEL_TYPE)
    start_date = forms.DateField(label="Start date", initial=datetime.datetime.now(),
                                 widget=DateInput(format='%Y-%m-%d',
                                                  attrs={'class': "input", 'placeholder': "yyyy/mm/dd"}))
    end_date = forms.DateField(label="End date", widget=DateInput(format='%Y-%m-%d', attrs={'class': "input",
                                                                                            'placeholder': "yyyy/mm/dd"}))
    budget = forms.CharField(label="Enter budget: ", max_length=15)


class add_groups(forms.Form):
    name = forms.CharField(label="Name:", max_length=100)
    status = forms.ChoiceField(label="Status", choices=STATUS_CHOICES)
    campaign_id = forms.ChoiceField(choices=CAMPAIGN_CHOICES)


class get_groups(forms.Form):
    campaign_id = forms.ChoiceField(choices=CAMPAIGN_CHOICES)


class add_keywords(forms.Form):
    text = forms.CharField(label="Keyword:", max_length=100)
    status = forms.ChoiceField(label="Status", choices=STATUS_CHOICES)

    # campaign=forms.ChoiceField(choices=CAMPAIGN_CHOICES)
    group = forms.ChoiceField(choices=GROUP_CHOICES)


class rule_keywords_form(forms.Form):
    keyword_id = forms.ChoiceField(label="Keyword", choices=KEYWORD_CHOICES)
    max_cpc = forms.IntegerField(label="Max CPC greater than", required=False)
    impressions = forms.IntegerField(label="Impressions less than", required=False)
    action = forms.ChoiceField(choices=(('ENABLED', 'Enable keywords'), ('PAUSED', 'Pause keywords')), label="Actions")


class rule_adgroups_form(forms.Form):
    group_id = forms.ChoiceField(label="Group name", choices=GROUP_CHOICES)
    max_ctr = forms.IntegerField(label="Max CTR", required=False)
    location = forms.CharField(label="Location", required=False)
    target_date = forms.DateField(label="Target date", widget=AdminDateWidget, required=False)
    action = forms.ChoiceField(choices=(('ENABLED', 'Enable adgroup'), ('PAUSED', 'Pause adgroup')), label="Actions")


class rule_campaign_form(forms.Form):
    keyword_id = forms.ChoiceField(choices=KEYWORD_CHOICES)
    max_cpc = forms.IntegerField(label="Max CPC", required=False)
    impressions = forms.IntegerField(label="Max Impressions", required=False)
    action = forms.ChoiceField(choices=(('ENABLED', 'Enable keywords'), ('PAUSED', 'Pause keywords')), label="Actions")


class recipe_settings_form(forms.Form):
    created_by = forms.CharField(label="Enter Your name:", max_length=100)
    recipe_name = forms.CharField(label="Enter Recipe name:", max_length=100)
    campaign_filter = forms.ChoiceField(choices=FILTER_CHOICES, label="Campaign Status", required=False)
    adgroup_filter = forms.ChoiceField(choices=FILTER_CHOICES, label="Adgroup Status", required=False)
    keyword_filter = forms.ChoiceField(choices=FILTER_CHOICES, label="Keyword Status", required=False)


class recipe_dash_form(forms.Form):
    recipe = forms.ChoiceField(choices=[], label="YOUR RECIPIES")

    def __init__(self, *args, **kwargs):
        super(recipe_dash_form, self).__init__(*args, **kwargs)
        self.fields['recipe'].choices = [(r.id, r.recipe_name) for r in Rule_Engine_Recipe.objects.all()]
        self.fields['recipe'].choices.append((None, 'Select Recipe'))


class adscheduler_form(forms.Form):
    campaign_name = forms.ChoiceField(choices=CAMPAIGN_CHOICES)
    days = forms.ChoiceField(choices=days, label="Days")
    starttime = forms.ChoiceField(choices=time, label="Start Time")
    endtime = forms.ChoiceField(choices=time, label="End Time")

    def clean(self):

        cleaned_data = super(adscheduler_form, self).clean()
        day = cleaned_data.get("days")
        start = cleaned_data.get("starttime")
        end = cleaned_data.get("endtime")
        if day:
            # print("====================", cleaned_data)
            if int(start) >= int(end):
                print("helllooo", type(start), end)
                raise forms.ValidationError("Start time cannot come after end time.")

        return cleaned_data
    # def __init__(self, *args, **kwargs):
    #     super(adscheduler, self).__init__(*args, **kwargs)
    #     self.fields['days'].choices = [d for d in days]
    #     self.fields['starttime'].choices = [t for t in time]
    #     self.fields['endtime'].choices = [t for t in time]
    # self.fields['recipe'].choices.append((None, 'Select Recipe'))

googleadwordssamad/myproject/templates/myproject/add.html
<form method="POST">
    {% csrf_token %}
    <legend> Add Campaign </legend><br><br>
    <fieldset >
        {{ add_campaign_form.as_p }}

    </fieldset>
    <input type="submit" value="Add">
  </form>

googleadwordssamad/myproject/templates/myproject/adscheduler.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
<link href="{% static 'js/app.js' %}">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>

<form method="POST">
    {% csrf_token %}
    <legend><h1> Welcome to the Ad Scheduler</h1> </legend><br><br>
    Select Campaign : {{ adscheduler.campaign_name }}
    <br><br>
<div id="data">
    <div id="0">
<!--        {{ adscheduler.days }}-->
<!--        {{ adscheduler.starttime }}-->
<!--        {{ adscheduler.endtime }}-->

        </div>
     {% for error in adscheduler.non_field_errors  %}
            {{ error }}
        {% endfor  %}
</div>


<input type="button" id="add" value="Add">
    <input id="save" type="submit" value="Save" name="btn_adscheduler">
<!--        <a href="{% url 'createRecipe' %}">Build your own</a>-->
  </form>
<script>
$(document).ready(function() {
console.log("selected",$('#id_campaign_name').val().length);
 $("#add").attr("disabled", true);
  $("#save").attr("disabled", true);
var count=0
$("#add").click(function(event){
        alert($("#id_campaign_name").val());
         count++;
         console.log(count);
         var st = '{{ adscheduler.days | escapejs }}';
         var elm = document.createElement('div');
            elm.setAttribute("id", count);
            elm.setAttribute("class", 'input');
            elm.innerHTML="{{ adscheduler.days | escapejs }}&nbsp;{{ adscheduler.starttime | escapejs }}&nbsp;{{ adscheduler.endtime | escapejs }}&nbsp;&nbsp;"
             document.getElementById('data').appendChild(elm);
             document.getElementById(count).innerHTML+='<input type=button class=cross value=x>'
});
$('#id_campaign_name').change(function() {
if($('#id_campaign_name').val().length!=0){
count=0;
document.getElementById('data').innerHTML='';
$("#add").removeAttr("disabled");
$("#save").removeAttr("disabled");
     $.ajax({
                type: "POST",
                url: "/adscheduler/",
                data: {
                    'campaign_id': $(this).val(),
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(data) {


                   for (var i = 1; i <= data.days.length; i++) {

             var elm = document.createElement('div');
            elm.setAttribute("id", i);
            elm.setAttribute("class", 'input');
            elm.innerHTML="{{ adscheduler.days | escapejs }}&nbsp;{{ adscheduler.starttime | escapejs }}&nbsp;{{ adscheduler.endtime | escapejs }}&nbsp;&nbsp;"
             document.getElementById('data').appendChild(elm);
             document.getElementById(i).innerHTML+='<input type=button class=cross value=x>'
             console.log('data.days:',data.days[i],",type:",typeof(data.days));
              $("#"+i).find("#id_days").val(data.days[i-1]);
              $("#"+i).find("#id_starttime").val(data.starttime[i-1]);
              $("#"+i).find("#id_endtime").val(data.endtime[i-1]);
            console.log("count:",count);
            count=i;

                    }

                }
            });
            }
});

{% if saved  %}
     $('#id_campaign_name').val("");
{% endif %}

$("#data").on('click', '.cross', function(){
    var parent_id=$(this).parent().attr('id');
    document.getElementById(parent_id).remove();
    count--;
            $('.input').each(function (i) {
                 $(this).attr('id',i+1);
                });
}) ;


});
</script>



</body>
</html>

googleadwordssamad/myproject/templates/myproject/ajax_action.html
<option>Actions</option>
{% for v in action_dictionary %}
    <option value="{{ v.1 }}">{{ v.0 }}</option>
         {% endfor %}}

googleadwordssamad/myproject/templates/myproject/ajax_action_options.html
<option>-------</option>

{% for v in action_options %}
    <option value="{{ v.1 }}" >{{ v.0 }}</option>
         {% endfor %}}

googleadwordssamad/myproject/templates/myproject/campaigns.html
<form method="POST">
    {% csrf_token %}
    <legend> Add Campaign </legend><br><br>
    <fieldset >
        {{ add_campaign_form.as_p }}

    </fieldset>
    <input type="submit" value="Add" name="btn_add_campaign">
  </form>

<br>
<legend> Campaign </legend>
<form action="/myproject/show/">

    <input type="submit" value="Show all Campaigns" name="btn_show_campaign"/>
</form>
<br>


{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

googleadwordssamad/myproject/templates/myproject/condition.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <title>Title</title>
</head>
<body>
<div id="conditions_div">
<br>



<center>
<button name="attribute_operand" type="button"  id="attribute_operand">Select Value</button>
<button name="attribute_operation" type="button" id="attribute_operation">operation</button>
<button name="value_operand" type="button" id="value_operand">Select Value</button></center>
<br><br><br><br>

<select name="current_scope" id="select_scope">

  <option value="Campaign">Campaign</option>
  <option value="Groups">Adgroups</option>
  <option value="Keywords">keywords</option>
</select>
<select name="date_range" id="date_range">

  <option value="Today">Today</option>
  <option value="Yesterday">Yesterday</option>
  <option value="This Month">This Month</option>
  <option value="Last Month">Last Month</option>
  <option value="Last 7 days">Last 7 days</option>
  <option value="Last 14 days">Last 14 days</option>
  <option value="Last 30 days">Last 30 days</option>



</select>
<input id="submit_btn" type="button" value="Next" style=" padding: 5px 5px 5px 5px; margin: 10px 10px 10px 10px; font-size: 16px; float:right;">

<br><br><br>

<div id="attributes_div">

    {% for e in fields %}
        <button   class="field_btn" tagvalue="{{ e.1 }}" value="{{ e.2 }}" style="padding: 5px 5px 5px 5px; margin: 10px 10px 10px 10px;">{{ e.0 }}</button>
        <div style="width:5px; height:auto; display:inline-block;"></div>
   {% endfor %}

</div>

<div id="operations_div_string">
    {% for key,value in operations.items %}
    {% if key == 'string' %}
        {% for k,v in value.items %}
    <button  name="field" class="operation_btn" tagvalue="{{ k }}" style="padding: 5px 5px 5px 5px; margin: 10px 10px 10px 10px;">{{ v }}</button>
        <div style="width:5px; height:auto; display:inline-block;"></div>

        {% endfor %}

    {% endif %}
    {% endfor %}


</div>

<div id="operations_div_number">



    {% for key,value in operations.items %}


     {% if key == 'number' %}
        {% for k,v in value.items %}

    <button  name="field" class="operation_btn" tagvalue="{{ k }}" style="padding: 5px 5px 5px 5px; margin: 10px 10px 10px 10px;">{{ v }}</button>
        <div style="width:5px; height:auto; display:inline-block;"></div>


    {% endfor %}

    {% endif %}
    {% endfor %}


</div>

<div id="operations_div_label">



    {% for key,value in operations.items %}
     {% if key == 'label' %}
            {% for k,v in value.items %}

    <button  name="field" class="operation_btn" tagvalue="{{ k }}" style="padding: 5px 5px 5px 5px; margin: 10px 10px 10px 10px;">{{ v }}</button>
        <div style="width:5px; height:auto; display:inline-block;"></div>
        {% endfor %}

    {% endif %}
    {% endfor %}



</div>



<div id="value_div_string">
<center>
  Enter String:<br>
  <input type="text" class="value_text">
<!--    <button   style="padding: 5px 5px 5px 5px; margin: 10px 10px 10px 10px;">Next</button>-->
</center>

</div>
<div id="value_div_number">
<center>
  Enter Number:<br>
  <input type="text" class="value_text">
<!--    <button   style="padding: 5px 5px 5px 5px; margin: 10px 10px 10px 10px;">Next</button>-->
</center>

</div>

<div id="value_div_bidding">

    {% for key,value in values_operand.items %}
     {% if key == 'BiddingStrategyType' %}
            {% for v in value %}

    <button   class="values_btn" tagvalue="{{ v.1 }}" style="padding: 5px 5px 5px 5px; margin: 10px 10px 10px 10px;">{{ v.0 }}</button>
        <div style="width:5px; height:auto; display:inline-block;"></div>
        {% endfor %}

    {% endif %}
    {% endfor %}


</div>
<div id="value_div_advertising">

    {% for key,value in values_operand.items %}
     {% if key == 'AdvertisingChannelType' %}
            {% for v in value %}

    <button   class="values_btn" tagvalue="{{ v.1 }}" style="padding: 5px 5px 5px 5px; margin: 10px 10px 10px 10px;">{{ v.0 }}</button>
        <div style="width:5px; height:auto; display:inline-block;"></div>
        {% endfor %}

    {% endif %}
    {% endfor %}

</div>
<div id="value_div_matchtype">

    {% for key,value in values_operand.items %}
     {% if key == 'KeywordMatchType' %}
            {% for v in value %}

    <button   class="values_btn" tagvalue="{{ v.1 }}" style="padding: 5px 5px 5px 5px; margin: 10px 10px 10px 10px;">{{ v.0 }}</button>
        <div style="width:5px; height:auto; display:inline-block;"></div>
        {% endfor %}

    {% endif %}
    {% endfor %}

</div>



<script>
    $(document).ready(function() {
                        $("#submit_btn").hide();
        $("#submit_btn").attr("disabled", true);;
        $("#value_div_bidding").hide();
             $("#value_div_advertising").hide();
             $("#value_div_matchtype").hide();
             $("#value_div_number").hide();
             $("#value_div_string").hide();
        $("#select_scope").hide();
        $("#date_range").hide();
        $("#attributes_div").hide();

        $("#attribute_operand").click(function(event) {
            $("#select_scope").show();
                    $("#date_range").show();
                    $("#submit_btn").show();

            $("#attributes_div").show();
            $("#operations_div_string").hide();
            $("#operations_div_number").hide();
            $("#operations_div_label").hide();
             $("#value_div_bidding").hide();
             $("#value_div_advertising").hide();
             $("#value_div_matchtype").hide();
             $("#value_div_number").hide();
             $("#value_div_string").hide();
        });

        $("#value_operand").click(function(event) {
            $("#attributes_div").hide();



            $("#operations_div_string").hide();
            $("#operations_div_number").hide();
            $("#operations_div_label").hide();

           if ($("#attribute_operand").attr('tagvalue')=='BiddingStrategyType')
           {
            $("#value_div_bidding").show();
           }
           else if ($("#attribute_operand").attr('tagvalue')=='AdvertisingChannelType')
           {
            $("#value_div_advertising").show();
           }
           else if ($("#attribute_operand").attr('tagvalue')=='KeywordMatchType')
           {
            $("#value_div_matchtype").show();
           }
           else if ($("#attribute_operand").attr('value')=='number')
           {
            $("#value_div_number").show();
           }
           else if ($("#attribute_operand").attr('value')=='string')
           {
               $("#value_div_string").show();
           }
           else if ($("#attribute_operand").attr('value')=='label')
           {
               $("#value_div_string").show();
           }

        });

        $("#attributes_div").on('click', '.field_btn', function() {

            $("#attribute_operand").text($(this).text());
            $("#attribute_operand").attr('tagvalue',$(this).attr('tagvalue'))
            $("#attribute_operand").val($(this).val());
            $("#attribute_operation").val($(this).val());
            $("#attribute_operation").text('operation');



        });
          $("#value_div_bidding").on('click', '.values_btn', function() {

            $("#value_operand").text($(this).text());
            $("#value_operand").attr('tagvalue',$(this).attr('tagvalue'));
                    $("#submit_btn").removeAttr("disabled");

        });
          $("#value_div_advertising").on('click', '.field_btn', function() {

             $("#value_operand").text($(this).text());
            $("#value_operand").attr('tagvalue',$(this).attr('tagvalue'))
            $("#submit_btn").removeAttr("disabled");



        });
          $("#value_div_matchtype").on('click', '.field_btn', function() {

             $("#value_operand").text($(this).text());
            $("#value_operand").attr('tagvalue',$(this).attr('tagvalue'))
            $("#submit_btn").removeAttr("disabled");



        });
        $('.value_text').on('input',function(e){
            $("#value_operand").text($(this).val());
             $("#value_operand").attr('tagvalue',$(this).val())
             $("#submit_btn").removeAttr("disabled");
});




        $("#operations_div_string").hide();
        $("#operations_div_number").hide();
        $("#operations_div_label").hide();

        $("#attribute_operation").click(function() {

            if ($(this).attr('value') == 'string') {
                $("#operations_div_string").show();
            } else if ($(this).attr('value') == 'number') {
                $("#operations_div_number").show();
            }
            if ($(this).attr('value') == 'label') {
                $("#operations_div_label").show();
            }


            $("#attributes_div").hide();
             $("#value_div").hide();

        });

        $(".operation_btn").click(function() {
            $("#attribute_operation").text($(this).text());
            $("#attribute_operation").attr('tagvalue',$(this).attr('tagvalue'));

        });


        $("#submit_btn").click(function() {
         $.ajax({
      type: "POST",
      url: "/addRules/",
      data: {
      current_scope : $('#select_scope').val(),
      date_range : $('#date_range').val(),
      attribute_operand : $('#attribute_operand').attr('tagvalue'),
      attribute_operation : $('#attribute_operation').attr('tagvalue'),
      operation_type : $('#attribute_operation').attr('value'),
      value_operand : $('#value_operand').attr('tagvalue')
      }
      ,
      success: function(result){
        alert("Rule added");
        alert(JSON.stringify(result));
        window.location.href = '/addRules/';
      }
    });


        });


        $('#select_scope').change(function() {
            $("#operations_div_string").hide();
            $("#operations_div_number").hide();
            $("#operations_div_label").hide();
            $("#value_div").hide();
            var value = $(this).val();
            var attr_div = $('#attributes_div').html();

            $.ajax({
                type: "POST",
                url: "/condition/",
                data: {
                    'current_scope': value,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(data) {

                    $('#attributes_div').html(data);


                    $("#attributes_div").show();




                }
            });
        });

    });
</script>
</div>
</body>
</html>


googleadwordssamad/myproject/templates/myproject/groups.html

<form method="POST">
    {% csrf_token %}
    <legend> Add Group </legend><br><br>
    <fieldset >
        {{ add_group_form.as_p }}

    </fieldset>
    <input type="submit" value="Add" name="btn_addgroup">
  </form>
<form method="POST">
    {% csrf_token %}
    <legend> Get Groups </legend><br><br>
    <fieldset >
        {{ get_group_form.as_p }}

    </fieldset>
    campaignid_fk:{{ campaignid }}
    <br>


     {% for g in allgroups %}
        <strong>{{ g.name }}</strong><br>
        {% endfor %}






    <input type="submit" value="Get groups" name="btn_getgroup">
  </form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

googleadwordssamad/myproject/templates/myproject/keywords.html
<form method="POST">
    {% csrf_token %}
    <legend> Add Keyword </legend><br><br>
    <fieldset >
        {{ add_keyword_form.as_p }}

    </fieldset>
    <input type="submit" value="Add keyword" name="btn_addkeyword">
  </form>

<legend> Keywords </legend>
<form action="/myproject/showkeywords/">

    <input type="submit" value="Show all keywords" name="btn_show_keywords"/>
</form>
<br>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

googleadwordssamad/myproject/templates/myproject/main.html
<body style="overflow-y: scroll;">
Welcome to google adwords project

<form action="/myproject/campaigns/">
    <input type="submit" value="Campaign section" />
</form>

<form action="/myproject/groups/">
    <input type="submit" value="Groups Section" />
</form>
<form action="/myproject/keywords/">
    <input type="submit" value="Keywords Section" />
</form>
<form action="/myproject/ruleEngine/">
    <input type="submit" value="Rule Engine" />
</form>
<form action="/recipe_dash/">
    <input type="submit" value="Create Recipe" />
</form>
<form action="/adscheduler/">
    <input type="submit" value="Ad Scheduler" />
</form>

<br><br>


{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<br><br><br><br><br>
</body>

googleadwordssamad/myproject/templates/myproject/recipe_dash.html

<form method="POST">
    {% csrf_token %}
    <legend><h1> Manage your recipes.</h1> </legend><br><br>
    <fieldset >
        {{ recipe_dash_form.as_p }}

    </fieldset>
    <input type="submit" value="Edit" name="btn_edit_recipe">
        <a href="{% url 'createRecipe' %}">Build your own</a>
  </form>

googleadwordssamad/myproject/templates/myproject/rule_campaign.html
<form method="POST">
    {% csrf_token %}
    <legend> Here you define scenarios for Campaigns </legend><br><br>
    <fieldset >
        {{ rule_campaign_form.as_p }}

    </fieldset>
    <input type="submit" value="Save" name="btn_add_rule">
  </form>

googleadwordssamad/myproject/templates/myproject/show.html
Show Campaign
 {% for campaigns in data %}
        <strong>{{ campaigns.name }}</strong>   {{ campaigns.status }}<br>
        {% endfor %}

googleadwordssamad/myproject/templates/myproject/showkeywords.html
Show Keywords<br>
 {% for k in keywords %}
        <strong>{{ k.text }}</strong>   {{ k.status }}<br>
        {% endfor %}